# Problem 1
Bir YetGenli yeni aldığı bahçesinin etrafına çit çevirmek istiyor. Bahçenin etrafını çit ile çevirmek için gerekli çit uzunluğunu ve bahçenin alanını hesaplayan fonksiyonu yazınız.

In [42]:
def citalan (a,b):
    alan= a*b
    return alan

def citcev (a,b):
    cevre = (a+b)*2
    return cevre
 
print (f" Bahçe alanı : {citalan(5,7)} ")
print (f" Gerekli çit uzunluğu : {citcev (5,7)} ")

 Bahçe alanı : 35
 Gerekli çit uzunluğu : 24

# Problem 2
Kendisine gönderilen 2 sayı arasındaki tüm asal sayıları bulan fonksiyonu yazınız.

In [60]:
#fonksiyonla yapamadım

In [54]:
num1 = int (input ("Sayı 1'i girin:"))
num2 = int ( input ( "Sayı 2'yi giriniz:"))

for num in range (num1, num2+1):
    if num > 1:
        for i in range (2,num):
            if (num % i) == 0:
                break
        else:
            print (num)

3
5
7
11

# Problem 3
YetGen liderlerinin kurdukları girişim unicorn oluyor. YetGen liderleri iş arkadaşlarının alacağı ücretlerini hesaplamak için bir fonksiyon yazdılar. Bu fonksiyonu kullanarak, YetGen liderlerinin iş arkadaşlarına verecekleri ücretleri hesaplayınız.

Ücret hesaplanması çalışma saatine bağlıdır. Bunun için kullanıcıdan çalışma saati bilgisinn alın. Sonrasında yapılacak ödemenin hesaplanacağı computePay() adlı bir fonksiyon oluşturun. Bu fonksiyonun içinde işlemler yapın. Çalışma saati 40 ve altındaysa saat başına ücret 10 TL’dir. 40 saatin üstünde çalışıldıysa saat başına ücret 15 TL sayılmaktadır.

```
Test etmek için 30 saat değerini giriniz,  sonuç 300 TL çıkmalı, 
ikincil test olarak 50 değerini giriniz,  sonuç 750 TL çıkmalı.
```

In [63]:
def computePay(calismasaati):
    if calismasaati<40:
        print(calismasaati*10)
    if calismasaati>40:
        print(calismasaati*15)
            
calismasaati=int(input("calisma saatini giriniz"))
computePay(calismasaati)

300

# Problem 4
YetGenliler zirveye gitmek için toplanıyor. Zirveye gitmek için kiraladıkları araçlar 4'er kişiliktir. Gelecek kişi sayısı için Airtable üzerinde form açılıyor. Gelecek kişi sayısını alıp dört kişilik araçlara bölüp kalan kişi sayısını döndüren bir fonksiyon yazınız.

In [72]:
def bölelim (sayimiz):
    print (sayimiz % 4)
bölelim (67)

3

# Problem 5
sayiTopla() adında bir fonksiyon yazın. sayiTopla() fonksiyonu girilen sayıları toplayarak yazdırmasını sağlayan bir fonksiyon yazınız.

Örneğin sayiTopla(1,2,3,4,5) yazdığımızda 15 çıktısını almalıyız. sayiTopla(1,2,3,4,5,6,7,8,9,10) yazdığımızda 55 çıktısını almalıyız.

In [69]:
def sayiTopla(*sayı):
    toplam=sum(sayı)
    print(toplam)
sayiTopla(1,2,3,4,5,6,7,8,9,10)

55

# Problem 6

[("xxx",1),("xxx",2),("xxx",9),("xxx",3), ("xxx",1),("xxx",13),("xxx",26),("xxx",4)] listesi içerisinde verilen elemanların her birini tuple içindeki 2. Elemana göre sıralayınız.

In [70]:
liste=[("xxx",1),("xxx",2),("xxx",9),("xxx",3), ("xxx",1),("xxx",13),("xxx",26),("xxx",4)]
liste.sort()
print(liste)

[('xxx', 1), ('xxx', 1), ('xxx', 2), ('xxx', 3), ('xxx', 4), ('xxx', 9), ('xxx', 13), ('xxx', 26)]

# Problem 7
List comprehension kullanarak 1'den 100'e kadar olan sayılardan sadece çift sayıları bir listeye atmayı yapmayı çalışın.

In [71]:
liste1=range(1,100)
liste2=[i for i in liste1 if (i%2==0)]
print(liste2)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]